export const GET_ALL_PRODUCTS="GET_ALL_PRODUCTS"
export const FILTER_PRODUCTS_BY_SIZE="FILTER_PRODUCTS_BY_SIZE";
export const SORT_PRODUCTS_BY_PRICE="SORT_PRODUCTS_BY_PRICE";
export const FILTER_AND_SORT="FILTER_AND_SORT";